name: myr_simulation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.25
  - numpy=2.0.1
  - scipy=1.13.1
  - pandas=2.3.3
  - scikit-learn
  - pip
  - pip:
    - dill
    - gspread
    - google-auth
    - google-auth-oauthlib